### ISSUE TITLE
Can't edit any SAML messages

### ISSUE THREAD

**Issue by bonkc** [SAMLRaider/SAMLRaider#35] opened 2019-03-29 15:58 UTC
Currently running Burp 2.0.19beta w/ openjdk on Ubuntu 16.10

SAML Raider seems to load fine and decode messages in the Proxy view. However the edit messages window doesn't allow entry of text. I can highlight text with my pointer and right click to "delete" and "copy/cut" but it doesn't actually edit the message before forwarding it on, or repeating the request in the repeater window. I have no errors in the extender tab.

I'm testing an instance of a nodejs app w/ passport-saml. Nothing crazy.

**Comment by mindfuckup** [comment] 2019-04-01 11:36
Hi

Do you use the bundled version of Burp (with the integrated OpenJDK 11) or do you use the Burp JAR file with the OpenJDK from Ubuntu?

Which version do you use? Portswigger just released a patch for some OpenJDK issues several days ago. Can you try the current version from the BApp store?

Thanks,
Emanuel

**Comment by mindfuckup** [comment] 2019-04-01 12:06
Hi

I just could reproduce your problem with the most current bundled Burp version and the most current SAML Raider version from the BApp store.

**Comment by mindfuckup** [comment] 2019-04-01 13:03
Update: It's an RSyntaxTextArea issue: https://github.com/bobbylight/RSyntaxTextArea/issues/197

**Comment by mindfuckup** [comment] 2019-04-01 16:41
Fixed in newer release https://github.com/SAMLRaider/SAMLRaider/releases/tag/v1.2.3.

I removed the RSyntaxTextArea because it is not possible to handle multiple instances. It's an issue of this library. Switched back to normal Java Swing JTextArea. There is no syntax highlighting or text search anymore. May be implemented again in the future. The most important thing is that the extension works again :)

**Closed by mindfuckup** 2019-04-01 16:41 UTC

**Comment by bonkc** [comment] 2019-04-02 18:47
Thanks for the fast fix. Awesome tool. :)

**Comment by mindfuckup** [comment] 2019-04-02 18:55
You're welcome & thanks for the feedback ;-)

**Comment by mindfuckup** [comment] 2019-04-02 18:57
Btw: It may endure some days until it's updated in the Burp BApp store. In the meantime, you can grab a fresh version from the release page here: https://github.com/SAMLRaider/SAMLRaider/releases/tag/v1.2.3.

**Comment by ozzi-** [comment] 2020-04-27 15:25
Burp 2020v4 fixes the issue with rsyntaxtextarea:
Check the latest answer of portswigger
https://forum.portswigger.net/thread/burp-suite-2-and-rsyntaxtextarea-library-5316570c

**Comment by mindfuckup** [comment] 2020-04-27 18:52
THX for the info. I'll maybe add it again. :)
